from __future__ import annotations

from enum import StrEnum


class Confidence(StrEnum):
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"


class FieldRole(StrEnum):
    INPUT = "input"
    OUTPUT = "output"
    INPUT_OUTPUT = "input_output"
    HIDDEN = "hidden"
    IGNORED = "ignored"
    ERROR_MESSAGE = "error_message"


class FieldType(StrEnum):
    STRING = "string"
    INTEGER = "integer"
    NUMBER = "number"
    BOOLEAN = "boolean"
    DATE = "date"
    TIME = "time"
    DATETIME = "datetime"


class WarningCode(StrEnum):
    FIELD_NAMES_INFERRED = "FIELD_NAMES_INFERRED"
    PLAIN_TEXT_ONLY_TRACE = "PLAIN_TEXT_ONLY_TRACE"
    SUBFILE_LIKE_REGION_DETECTED = "SUBFILE_LIKE_REGION_DETECTED"
    FUNCTION_KEY_ONLY_SCREEN = "FUNCTION_KEY_ONLY_SCREEN"
    VOLATILE_REGION_NOT_DECLARED = "VOLATILE_REGION_NOT_DECLARED"
    REPEATED_SCREEN_HASH = "REPEATED_SCREEN_HASH"
    HIDDEN_FIELDS_NOT_CAPTURED = "HIDDEN_FIELDS_NOT_CAPTURED"
    GENERATED_COORDINATE_NAMES = "GENERATED_COORDINATE_NAMES"
    OUTPUT_FIELD_SELECTION_REQUIRES_REVIEW = "OUTPUT_FIELD_SELECTION_REQUIRES_REVIEW"
    ERROR_SCREEN_RECORDED = "ERROR_SCREEN_RECORDED"
    UNSUPPORTED_AID = "UNSUPPORTED_AID"


class BlockerCode(StrEnum):
    NO_SCREEN_EVENTS = "NO_SCREEN_EVENTS"
    NO_ACTION_EVENTS = "NO_ACTION_EVENTS"
    NO_INPUT_FIELDS = "NO_INPUT_FIELDS"
    NO_FINAL_OUTPUT_FIELDS = "NO_FINAL_OUTPUT_FIELDS"
    AMBIGUOUS_FIELD_COORDINATES = "AMBIGUOUS_FIELD_COORDINATES"
    TRACE_SEQUENCE_INVALID = "TRACE_SEQUENCE_INVALID"
    FIELD_MAP_INVALID = "FIELD_MAP_INVALID"
    MULTI_PATH_FLOW_NOT_SUPPORTED_IN_MVP = "MULTI_PATH_FLOW_NOT_SUPPORTED_IN_MVP"
    SCREEN_SIZE_INVALID = "SCREEN_SIZE_INVALID"
    FIELD_COORDINATES_OUT_OF_BOUNDS = "FIELD_COORDINATES_OUT_OF_BOUNDS"
    GENERATED_COORDINATE_NAMES_IN_STRICT_MODE = "GENERATED_COORDINATE_NAMES_IN_STRICT_MODE"


SUPPORTED_AIDS = {
    "ENTER",
    "CLEAR",
    "RESET",
    "HELP",
    "PAGEUP",
    "PAGEDOWN",
    *{f"F{i}" for i in range(1, 25)},
}


def generated_field_id(row: int, col: int) -> str:
    return f"f_{row:02d}_{col:02d}"


def screen_ref_for_seq(seq: int) -> str:
    return f"screen_{seq:03d}"
