from __future__ import annotations

import os
import shlex
from pathlib import Path

from .config import ensure_parent
from .models import QualificationResult
from .readiness import readiness_lane, release_lane_description


SLURM_FRAGMENT_HEADER = [
    "# Generated by gpu-rack-qualifier.",
    "# Review-only output. This file was not applied.",
    "# Do not copy into production without administrator review.",
    "# The tool does not know your full Slurm topology, partitions, GRES, or site policy.",
]

DRAIN_REVIEW_HEADER = [
    "#!/usr/bin/env bash",
    "# Review-only suggested commands.",
    "# This script was not executed.",
    "# Remove comments only after operator approval.",
    "# The tool does not know current Slurm state.",
]


def render_slurm_fragment(path: Path, results: list[QualificationResult]) -> None:
    ensure_parent(path)
    lines = list(SLURM_FRAGMENT_HEADER)
    for result in sorted(results, key=lambda item: item.features.node_name):
        node = result.features.node_name
        features = ",".join(result.slurm_features)
        lane = readiness_lane(result)
        lines.append(f"# ReadinessLane={lane} Meaning={release_lane_description(lane)}")
        lines.append(f"# NodeName={node} Features={features}")
        if result.features.gpu_count is not None:
            lines.append(f"# Inventory says gpu count = {result.features.gpu_count}. This tool does not change GRES.")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def render_drain_review(path: Path, results: list[QualificationResult]) -> None:
    ensure_parent(path)
    lines = list(DRAIN_REVIEW_HEADER)
    emitted = False
    for result in sorted(results, key=lambda item: item.features.node_name):
        if result.recommended_state not in {"DRAIN_REVIEW", "QUARANTINE_REVIEW"}:
            continue
        emitted = True
        primary = (result.features.blockers or result.features.warnings or ["review"])[0]
        reason = f"rackq: {primary.replace('_', ' ').lower()}; review before scheduling"
        lines.append(f"# scontrol update NodeName={result.features.node_name} State=DRAIN Reason={shlex.quote(reason)}")
    if not emitted:
        lines.append("# No drain-review candidates from this run.")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    current = path.stat().st_mode
    path.chmod(current & ~0o111)
